#!/usr/bin/env python3
"""
CGMND Dataset Singer Tap
=========================
Singer tap for the (CGMND) dataset.
- Input: participant.csv, cgm_file_metadata.csv, study.csv (generated by cgmnd-content-generator.py)
- Output: Standard Singer messages (SCHEMA, RECORD, STATE)
"""

import sys
import os
import csv
import json
import logging
import uuid
import re
import argparse
import subprocess
import venv
from datetime import datetime, timezone
from typing import Optional
import importlib.resources


# --- 1. BOOTSTRAPPING & VENV ---
def bootstrap_venv():
    """Ensure the script runs within a project-standard virtual environment."""
    if sys.prefix != sys.base_prefix:
        return  # Already in venv

    script_path = os.path.abspath(__file__)
    script_dir = os.path.dirname(script_path)  # singer-tap
    project_root = os.path.dirname(script_dir)  # drh-edge-core
    platform_root = os.path.dirname(project_root)  # spry-drh-edge-platform

    venv_dir = os.path.join(project_root, ".venv")
    req_file = os.path.join(platform_root, "requirements.txt")

    if sys.platform == "win32":
        venv_python = os.path.join(venv_dir, "Scripts", "python.exe")
    else:
        venv_python = os.path.join(venv_dir, "bin", "python")

    if not os.path.exists(venv_python):
        print(f"DEBUG: Creating venv at {venv_dir}", file=sys.stderr)
        venv.EnvBuilder(with_pip=True).create(venv_dir)

    # Ensure dependencies are available
    check_cmd = [venv_python, "-c", "import drh_target, dotenv"]
    if (
        subprocess.call(check_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        != 0
    ):
        print(f"DEBUG: Installing from {req_file}...", file=sys.stderr)
        subprocess.check_call(
            [
                venv_python,
                "-m",
                "pip",
                "install",
                "--upgrade",
                "-r",
                req_file,
                "python-dotenv",
            ],
            stdout=subprocess.DEVNULL,
            stderr=sys.stderr,
        )

    os.environ["PYTHONUNBUFFERED"] = "1"
    print(f"DEBUG: Re-executing with {venv_python}", file=sys.stderr)
    os.execv(venv_python, [venv_python, script_path] + sys.argv[1:])


# Entry-point bootstrap
bootstrap_venv()

# --- 2. LOGGING & OTel ---
try:
    from dotenv import load_dotenv  # type: ignore

    _script_dir = os.path.dirname(os.path.abspath(__file__))
    _env_path = os.path.join(os.path.dirname(_script_dir), ".env")
    if os.path.exists(_env_path):
        load_dotenv(_env_path)
except ImportError:
    pass

logging.basicConfig(
    stream=sys.stderr, level=logging.INFO, format="%(levelname)s: %(message)s"
)
LOGGER = logging.getLogger("tap-cgmnd")


# Category Spans (High-level checks)
class OTelNames:
    # Root Span
    ROOT_VV = "V&V Orchestration Session"

    # Category Spans (High-level checks)
    CAT_FOLDER_SCAN = "1: Folder & Resource Scan"
    CAT_MANDATORY_FILES = "2: Mandatory File Presence"
    CAT_EXTENSION_CHECK = "3: File Extension Validation"
    CAT_SCHEMA_VALIDATION = "4: File Schema Check"
    CAT_CGM_TRACE_METADATA = "5: CGM Tracing Metadata Check"
    CAT_CGM_INTEGRITY = "6: CGM Data Integrity"
    CAT_MEAL_METADATA = "7: Meal Data Metadata Check"
    CAT_MEAL_INTEGRITY = "8: Meal Data Integrity"
    CAT_FITNESS_METADATA = "9: Fitness Metadata Check"
    CAT_FITNESS_INTEGRITY = "10: Fitness Data Integrity"

    # Sub-Spans for Schema Validation (Check 4)
    CHK_FILE_VAL = "4.1: File Validation"
    CHK_COLUMNS = "4.1.a: Required Columns"
    CHK_TYPE = "4.1.b: Type Check"
    CHK_PATTERNS = "4.1.c: Format & Pattern Check"
    CHK_FK_INTEGRITY = "4.1.d: Foreign Key Check"

    # Attributes
    ATTR_VALIDATION_LEVEL = "validation.level"
    ATTR_FILE_NAME = "file.name"
    ATTR_ERROR_COUNT = "error_count"
    ATTR_ROW_COUNT = "file.row_count"
    ATTR_STATUS = "check.status"
    ATTR_DETAILS = "details"

    # Metric Names
    METRIC_PASS_COUNT = "vv.validation.pass_count"
    METRIC_FAIL_COUNT = "vv.validation.fail_count"
    METRIC_FILE_COUNT = "vv.files.processed_count"
    METRIC_VALIDATION_DURATION = "vv.validation.duration"


# SDK / DRH Imports
# Ensure we can import the SDK from parent directory
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
try:
    from drh_target.loader import DRHLoader  # type: ignore
except ImportError:
    # Minimal fallback for testing if drh_target not reachable
    class DRHLoader:
        def __init__(self):
            pass

        def emit_record(self, stream, record):
            print(json.dumps({"type": "RECORD", "stream": stream, "record": record}))


def get_time_nano():
    return int(datetime.now(timezone.utc).timestamp() * 1e9)


def emit_otel_span(
    emitter,
    resource_id,
    name,
    start_time_nano,
    end_time_nano,
    parent_span_id=None,
    attributes=None,
    status_code="OK",
    span_id=None,
    trace_id=None,
):
    """Emits an OTel Span record."""
    if attributes is None:
        attributes = {}

    if not span_id:
        span_id = str(uuid.uuid4()).replace("-", "")[:16]

    if not trace_id:
        trace_id = str(uuid.uuid4()).replace("-", "")

    record = {
        "name": name,
        "trace_id": trace_id,
        "span_id": span_id,
        "parent_span_id": parent_span_id if parent_span_id else "",
        "start_time_unix_nano": start_time_nano,
        "end_time_unix_nano": end_time_nano,
        "attributes": attributes,
        "status_code": {"code": status_code},
        "resource_id": resource_id,
    }
    emitter.emit_record("otel_spans", record)
    return span_id, trace_id


def emit_otel_log(
    emitter, resource_id, severity, body, attributes=None, span_id="", trace_id=""
):
    """Emits an OTel Log record."""
    if attributes is None:
        attributes = {}

    # Map severity text to number (approximate)
    severity_map = {"DEBUG": 5, "INFO": 9, "WARN": 13, "ERROR": 17, "FATAL": 21}

    record = {
        "time_unix_nano": get_time_nano(),
        "trace_id": trace_id,
        "span_id": span_id,
        "severity_number": severity_map.get(severity, 9),
        "severity_text": severity,
        "body": str(body),
        "attributes": attributes,
        "resource_id": resource_id,
    }
    emitter.emit_record("otel_logs", record)


def emit_otel_metric(emitter, resource_id, name, value, unit="1", attributes=None):
    """Emits an OTel Metric data point."""
    if attributes is None:
        attributes = {}

    record = {
        "name": name,
        "description": f"Metric for {name}",
        "unit": unit,
        "time_unix_nano": get_time_nano(),
        "value": float(value),
        "attributes": attributes,
        "resource_id": resource_id,
    }
    emitter.emit_record("otel_metrics", record)


def emit_otel_resource(emitter):
    """Emits the OTel Resource definition and returns the resource_id."""
    resource_id = str(uuid.uuid4())
    record = {
        "resource_id": resource_id,
        "service.name": os.environ.get("OTEL_SERVICE_NAME", "tap-cgmnd"),
        "service.version": os.environ.get("OTEL_SERVICE_VERSION", "1.0.0"),
        "service.instance.id": resource_id,
        "deployment.environment": os.environ.get("DEPLOY_ENV", "production"),
        "singer.role": "tap",
        "singer.stream": "all",
    }
    emitter.emit_record("otel_resource", record)
    return resource_id





def load_schema(stream_name):
    """Load JSON schema for the specified stream."""
    try:
        fname = f"{stream_name}.json"
        with importlib.resources.open_text("drh_target.schemas", fname) as f:
            return json.load(f)
    except Exception as e:
        LOGGER.error(f"Failed to load schema for {stream_name}: {e}")
        return {}


ALL_STREAM_NAMES = [
    "cgm_file_metadata",
    "participant",
    "site",
    "study",
    "investigator",
    "institution",
    "lab",
    "author",
    "publication",
    "fitness_file_metadata",
    "meal_file_metadata",
    # "drh_validation_reports",
    # "drh_diagnostics",
    "cgm_tracing",
    "meal",
    "fitness",
    #"combined_cgm_tracing",
    "otel_resource",
    "otel_logs",
    "otel_metrics",
    "otel_spans",
]


def get_stream_keys():
    """Retrieve primary key properties for all streams from their schemas."""
    keys = {}
    for stream in ALL_STREAM_NAMES:
        schema = load_schema(stream)
        if schema and "key_properties" in schema:
            keys[stream] = schema["key_properties"]
        else:
            default_key = f"{stream}_id"
            if (
                schema
                and "properties" in schema
                and default_key in schema["properties"]
            ):
                keys[stream] = [default_key]
            elif schema and "properties" in schema and "id" in schema["properties"]:
                keys[stream] = ["id"]
            else:
                keys[stream] = []
    return keys


STREAM_KEYS = get_stream_keys()


def get_files_config():
    """Get mapping of stream names to filenames from environment or defaults."""
    files = {}
    for stream in ALL_STREAM_NAMES:
        env_var = f"{stream.upper()}_FILE"
        default_name = f"{stream}.csv"
        files[stream] = os.path.basename(os.environ.get(env_var, default_name))

    if "meal_data" not in files:
        files["meal_data"] = os.path.basename(
            os.environ.get("MEAL_DATA_FILE", "meal_data.csv")
        )
    if "fitness_data" not in files:
        files["fitness_data"] = os.path.basename(
            os.environ.get("FITNESS_DATA_FILE", "fitness_data.csv")
        )

    return files


FILES = get_files_config()

MANDATORY_STREAM_NAMES = [
    "participant",
    "institution",
    "lab",
    "study",
    "site",
    "investigator",
    "publication",
    "author",
    "cgm_file_metadata",
]

MANDATORY_FILE_CHECK_STREAMS = ["participant", "study", "cgm_file_metadata"]


def get_expected_headers():
    """Determine expected headers for each stream based on its schema."""
    headers = {}
    for stream in ALL_STREAM_NAMES:
        schema = load_schema(stream)
        if schema and "required" in schema:
            headers[stream] = schema["required"]
        else:
            headers[stream] = []
    return headers


EXPECTED_HEADERS = get_expected_headers()


# --- 3. LOADER & VALIDATION ---
class ValidatingDRHLoader(DRHLoader):
    """
    Extension of DRHLoader that validates records against Key Properties and Schema Required fields.
    """

    def __init__(self, otel_resource_id=None):
        super().__init__()
        self.schemas = {}
        self.otel_resource_id = otel_resource_id
        self.trace_id = str(uuid.uuid4()).replace("-", "")

    def load_schema_if_needed(self, stream_name):
        """Ensure schema for stream is loaded in the validator."""
        if stream_name not in self.schemas:
            self.schemas[stream_name] = load_schema(stream_name)
        return self.schemas[stream_name]

    def emit_record(self, stream_name, record):
        """Validate record against schema and emit Singer RECORD message."""
        # Prevent recursion: Don't validate/log errors for OTel streams themselves
        if stream_name.startswith("otel_"):
            super().emit_record(stream_name, record)
            return

        # Ensure schema is loaded
        schema = self.load_schema_if_needed(stream_name)

        # 1. Check Key Properties (Primary Keys)
        key_props = STREAM_KEYS.get(stream_name, [])
        if key_props:
            missing_keys = [
                k for k in key_props if k not in record or record.get(k) is None
            ]
            # Filter out tenant fields from validation
            missing_keys = [
                k for k in missing_keys if k not in ("tenant_id", "tenant_name")
            ]

            if missing_keys:
                msg = f"Validation Error [Integrity]: Stream '{stream_name}' record missing KEY properties: {missing_keys}. Record skipped."
                LOGGER.error(msg)
                if self.otel_resource_id:
                    emit_otel_log(
                        self,
                        self.otel_resource_id,
                        "ERROR",
                        msg,
                        {"stream": stream_name, "error_type": "integrity"},
                    )
                return  # Skip emitting

        # 2. Check Required Fields (Mandatory Columns from Schema)
        if schema:
            required_fields = schema.get("required", [])
            if required_fields:
                missing_required = [
                    field for field in required_fields if field not in record
                ]
                # Filter out tenant fields
                missing_required = [
                    k for k in missing_required if k not in ("tenant_id", "tenant_name")
                ]

                if missing_required:
                    msg = f"Validation Error [Schema]: Stream '{stream_name}' record missing REQUIRED fields: {missing_required}. Record skipped."
                    LOGGER.error(msg)
                    if self.otel_resource_id:
                        emit_otel_log(
                            self,
                            self.otel_resource_id,
                            "ERROR",
                            msg,
                            {
                                "stream": stream_name,
                                "error_type": "schema",
                                "missing_fields": str(missing_required),
                            },
                        )
                    return  # Skip emitting

        # If validation passes, emit normally
        super().emit_record(stream_name, record)


class ForeignKeyValidator:
    """
    Validates Foreign Keys across all streams.
    Phase 1: Collection (during file reading)
    Phase 2: Global Validation (after all files read)
    """

    def __init__(self):
        # Maps stream_name -> set of collected IDs (Primary Keys)
        self.stream_ids = {}
        # List of pending checks: (source_stream, source_row_num, target_stream, target_id_value, field_name)
        self.pending_fks = []
        # Maps stream_name -> list of FK definitions from schema
        self.schema_refs = {}

    def register_schema(self, stream_name, schema):
        """Parse schema to identify Foreign Key relationships."""
        if stream_name in self.schema_refs:
            return

        self.schema_refs[stream_name] = []
        properties = schema.get("properties", {})

        for field_name, field_def in properties.items():
            # Support 1: Custom 'foreign_key' property
            fk_target = field_def.get("foreign_key")

            # Support 2: Standard JSON Schema '$ref'
            if not fk_target and "$ref" in field_def:
                ref = field_def["$ref"]
                match = re.match(r"^([a-zA-Z0-9_]+)\.json", ref)
                if match:
                    fk_target = match.group(1)

            if fk_target:
                self.schema_refs[stream_name].append(
                    {"field": field_name, "target_stream": fk_target}
                )

    def track_row(self, stream_name, row, filename, line_num):
        """
        1. Collect Primary Keys for this row.
        2. Record outgoing Foreign Keys for later validation.
        """
        # 1. Collect IDs
        pk_list = STREAM_KEYS.get(stream_name, [])

        for pk in pk_list:
            if pk in row and row[pk]:
                if stream_name not in self.stream_ids:
                    self.stream_ids[stream_name] = set()
                self.stream_ids[stream_name].add(row[pk])

        # 2. Track FKs
        if stream_name in self.schema_refs:
            for fk_def in self.schema_refs[stream_name]:
                field = fk_def["field"]
                target_stream = fk_def["target_stream"]

                val = row.get(field)
                if val:  # Only validate non-empty FKs
                    self.pending_fks.append(
                        {
                            "source_stream": stream_name,
                            "source_file": filename,
                            "line": line_num,
                            "field": field,
                            "value": val,
                            "target_stream": target_stream,
                        }
                    )

    def validate(self):
        """
        Global Validation Phase.
        Returns list of violation strings.
        """
        violations = []
        LOGGER.info(
            f"Starting Global FK Validation on {len(self.pending_fks)} references across {len(self.stream_ids)} streams..."
        )

        for check in self.pending_fks:
            target_stream = check["target_stream"]
            val = check["value"]

            if target_stream not in self.stream_ids:
                violations.append(
                    f"FK Violation in {check['source_file']} line {check['line']}: {check['field']}='{val}' refers to missing stream '{target_stream}'"
                )
                continue

            if val not in self.stream_ids[target_stream]:
                violations.append(
                    f"FK Violation in {check['source_file']} line {check['line']}: {check['field']}='{val}' not found in {target_stream}"
                )

        return violations


# --- 4. STATE MANAGEMENT ---
FILE_CACHE = None


def find_file(data_dir, filename):
    global FILE_CACHE
    if FILE_CACHE is None:
        import glob

        FILE_CACHE = {}
        for filepath in glob.glob(os.path.join(data_dir, "**", "*.*"), recursive=True):
            name = os.path.basename(filepath)
            if name not in FILE_CACHE:
                FILE_CACHE[name] = filepath
    return FILE_CACHE.get(filename, os.path.join(data_dir, filename))


def check_file_headers(
    data_dir,
    emitter=None,
    resource_id=None,
    parent_span_id=None,
    trace_id=None,
    fk_validator=None,
):
    """
    Check if existing files have required headers AND validate data formats.
    Returns a list of result dicts: {"name": str, "status": str, "details": str}
    """
    results = []

    for key, expected_cols in EXPECTED_HEADERS.items():
        fname = FILES.get(key)
        if not fname:
            continue

        fpath = find_file(data_dir, fname)
        if os.path.exists(fpath):
            file_span_id = None
            file_start_time = None
            if emitter and resource_id:
                # Start File Span
                file_start_time = get_time_nano()
                file_span_id = str(uuid.uuid4()).replace("-", "")[:16]

            try:
                with open(fpath, "r", encoding="utf-8-sig") as f:
                    reader = csv.reader(f)
                    try:
                        # --- 4.1.1 Required Columns Check ---
                        req_cols_start = get_time_nano()
                        req_cols_span_id = (
                            str(uuid.uuid4()).replace("-", "")[:16]
                            if (emitter and resource_id)
                            else None
                        )

                        header = next(reader)

                        # Build column-level status
                        col_status = []
                        missing_cols = []

                        for col in expected_cols:
                            if col in header:
                                col_status.append(f"{col}: OK")
                            else:
                                if col not in ("tenant_id", "tenant_name"):
                                    col_status.append(f"{col}: MISSING")
                                    missing_cols.append(col)
                                else:
                                    col_status.append(f"{col}: OPTIONAL(ENV)")

                        details = " | ".join(col_status)

                        if missing_cols:
                            # Required Columns FAILED
                            results.append(
                                {
                                    "name": f"File Schema - Required Columns: {fname}",
                                    "status": "FAILED",
                                    "details": details,
                                }
                            )
                            if emitter and resource_id:
                                # Emit Required Columns Span failure
                                emit_otel_span(
                                    emitter,
                                    resource_id,
                                    f"{OTelNames.CHK_COLUMNS}: {fname}",
                                    req_cols_start,
                                    get_time_nano(),
                                    parent_span_id=file_span_id,
                                    span_id=req_cols_span_id,
                                    attributes={
                                        OTelNames.ATTR_VALIDATION_LEVEL: "column_check",
                                        OTelNames.ATTR_FILE_NAME: fname,
                                        "missing": str(missing_cols),
                                    },
                                    status_code="ERROR",
                                    trace_id=trace_id,
                                )

                                # Emit File Span failure
                                emit_otel_span(
                                    emitter,
                                    resource_id,
                                    f"{OTelNames.CHK_FILE_VAL}: {fname}",
                                    file_start_time,
                                    get_time_nano(),
                                    parent_span_id=parent_span_id,
                                    span_id=file_span_id,
                                    attributes={
                                        OTelNames.ATTR_VALIDATION_LEVEL: "schema",
                                        OTelNames.ATTR_FILE_NAME: fname,
                                        "error": "Missing Columns",
                                    },
                                    status_code="ERROR",
                                    trace_id=trace_id,
                                )
                            continue
                        else:
                            # Required Columns PASSED
                            if emitter and resource_id:
                                emit_otel_span(
                                    emitter,
                                    resource_id,
                                    f"{OTelNames.CHK_COLUMNS}: {fname}",
                                    req_cols_start,
                                    get_time_nano(),
                                    parent_span_id=file_span_id,
                                    span_id=req_cols_span_id,
                                    attributes={
                                        OTelNames.ATTR_VALIDATION_LEVEL: "column_check",
                                        OTelNames.ATTR_FILE_NAME: fname,
                                    },
                                    status_code="OK",
                                    trace_id=trace_id,
                                )

                        # --- 4.1.2 Type Check & 4.1.3 Format & Pattern Check ---
                        data_val_start = get_time_nano()
                        type_span_id = (
                            str(uuid.uuid4()).replace("-", "")[:16]
                            if (emitter and resource_id)
                            else None
                        )
                        pattern_span_id = (
                            str(uuid.uuid4()).replace("-", "")[:16]
                            if (emitter and resource_id)
                            else None
                        )

                        schema = load_schema(key)
                        if fk_validator:
                            fk_validator.register_schema(key, schema)
                        properties = schema.get("properties", {})
                        header_map = {col: i for i, col in enumerate(header)}

                        row_errors = []
                        line_num = 1  # 1-based, starting after header

                        for row in reader:
                            line_num += 1
                            if fk_validator:
                                row_dict = {
                                    col: row[idx]
                                    for col, idx in header_map.items()
                                    if idx < len(row)
                                }
                                fk_validator.track_row(key, row_dict, fname, line_num)
                            for field_name, field_def in properties.items():
                                if field_name not in header_map:
                                    continue
                                idx = header_map[field_name]
                                if idx >= len(row):
                                    continue

                                val = row[idx].strip()
                                if not val:
                                    continue

                                # 1. Type Check
                                field_type = field_def.get("type")
                                if isinstance(field_type, list):
                                    field_type = (
                                        [t for t in field_type if t != "null"][0]
                                        if [t for t in field_type if t != "null"]
                                        else "string"
                                    )

                                if field_type == "integer":
                                    if not re.match(r"^-?\d+$", val):
                                        row_errors.append(
                                            f"Line {line_num} {field_name}: '{val}' is not an integer"
                                        )
                                elif field_type == "number":
                                    try:
                                        float(val)
                                    except ValueError:
                                        row_errors.append(
                                            f"Line {line_num} {field_name}: '{val}' is not a number"
                                        )
                                elif field_type == "boolean":
                                    if val.lower() not in ("true", "false", "1", "0"):
                                        row_errors.append(
                                            f"Line {line_num} {field_name}: '{val}' is not a boolean"
                                        )

                                # 2. Format Check
                                fmt = field_def.get("format")
                                if fmt == "date-time":
                                    if not re.match(r"^\d{4}-\d{2}-\d{2}", val):
                                        row_errors.append(
                                            f"Line {line_num} {field_name}: '{val}' is not a date-time"
                                        )
                                elif fmt == "date":
                                    if not re.match(r"^\d{4}-\d{2}-\d{2}", val):
                                        row_errors.append(
                                            f"Line {line_num} {field_name}: '{val}' is not a date"
                                        )

                                # 3. Pattern Check
                                pattern = field_def.get("pattern")
                                if pattern:
                                    is_excluded_file = any(
                                        x in fname
                                        for x in [
                                            "cgm_tracing",
                                            "fitness_data",
                                            "meal_data",
                                        ]
                                    )
                                    is_date_format = field_def.get("format") in [
                                        "date",
                                        "date-time",
                                    ]

                                    if is_excluded_file and is_date_format:
                                        pass
                                    else:
                                        try:
                                            if not re.match(pattern, val):
                                                row_errors.append(
                                                    f"Line {line_num} {field_name}: '{val}' does not match pattern '{pattern}'"
                                                )
                                        except re.error:
                                            pass

                            if len(row_errors) > 100:
                                row_errors.append("... (too many errors)")
                                break

                        data_val_end = get_time_nano()

                        # Emit Type and Pattern Spans
                        if emitter and resource_id:
                            sub_status = "ERROR" if row_errors else "OK"
                            err_attr = (
                                {"error_count": len(row_errors)} if row_errors else {}
                            )

                            emit_otel_span(
                                emitter,
                                resource_id,
                                f"{OTelNames.CHK_TYPE}: {fname}",
                                data_val_start,
                                data_val_end,
                                parent_span_id=file_span_id,
                                span_id=type_span_id,
                                attributes={
                                    OTelNames.ATTR_VALIDATION_LEVEL: "type_check",
                                    **err_attr,
                                },
                                status_code=sub_status,
                                trace_id=trace_id,
                            )

                            emit_otel_span(
                                emitter,
                                resource_id,
                                f"{OTelNames.CHK_PATTERNS}: {fname}",
                                data_val_start,
                                data_val_end,
                                parent_span_id=file_span_id,
                                span_id=pattern_span_id,
                                attributes={
                                    OTelNames.ATTR_VALIDATION_LEVEL: "pattern_check",
                                    **err_attr,
                                },
                                status_code=sub_status,
                                trace_id=trace_id,
                            )

                        # --- 4.1.4 Foreign Key Reference Collection ---
                        if emitter and resource_id:
                            fk_start = get_time_nano()
                            fk_span_id = str(uuid.uuid4()).replace("-", "")[:16]

                            emit_otel_span(
                                emitter,
                                resource_id,
                                f"{OTelNames.CHK_FK_INTEGRITY}: {fname}",
                                fk_start,
                                get_time_nano(),
                                parent_span_id=file_span_id,
                                span_id=fk_span_id,
                                attributes={
                                    OTelNames.ATTR_VALIDATION_LEVEL: "fk_collection"
                                },
                                status_code="OK",
                                trace_id=trace_id,
                            )

                        if row_errors:
                            results.append(
                                {
                                    "name": f"File Schema Check: {fname}",
                                    "status": "FAILED",
                                    "details": "; ".join(row_errors[:5]),
                                }
                            )
                            if emitter and resource_id:
                                emit_otel_span(
                                    emitter,
                                    resource_id,
                                    f"{OTelNames.CHK_FILE_VAL}: {fname}",
                                    file_start_time,
                                    get_time_nano(),
                                    parent_span_id=parent_span_id,
                                    span_id=file_span_id,
                                    attributes={
                                        OTelNames.ATTR_VALIDATION_LEVEL: "schema",
                                        OTelNames.ATTR_FILE_NAME: fname,
                                        OTelNames.ATTR_ERROR_COUNT: len(row_errors),
                                    },
                                    status_code="ERROR",
                                    trace_id=trace_id,
                                )
                        else:
                            results.append(
                                {
                                    "name": f"File Schema Check: {fname}",
                                    "status": "PASSED",
                                    "details": "Header & Data Validation OK",
                                }
                            )
                            if emitter and resource_id:
                                emit_otel_span(
                                    emitter,
                                    resource_id,
                                    f"{OTelNames.CHK_FILE_VAL}: {fname}",
                                    file_start_time,
                                    get_time_nano(),
                                    parent_span_id=parent_span_id,
                                    span_id=file_span_id,
                                    attributes={
                                        OTelNames.ATTR_VALIDATION_LEVEL: "schema",
                                        OTelNames.ATTR_FILE_NAME: fname,
                                    },
                                    status_code="OK",
                                    trace_id=trace_id,
                                )

                    except StopIteration:
                        # Handle Empty File
                        if emitter and resource_id and file_start_time:
                            req_cols_span_id = str(uuid.uuid4()).replace("-", "")[:16]
                            req_cols_start = file_start_time
                            emit_otel_span(
                                emitter,
                                resource_id,
                                f"{OTelNames.CHK_COLUMNS}: {fname}",
                                req_cols_start,
                                get_time_nano(),
                                parent_span_id=file_span_id,
                                span_id=req_cols_span_id,
                                attributes={
                                    OTelNames.ATTR_VALIDATION_LEVEL: "column_check",
                                    "error": "Empty File",
                                },
                                status_code="ERROR",
                                trace_id=trace_id,
                            )

                        results.append(
                            {
                                "name": f"File Schema Check: {fname}",
                                "status": "FAILED",
                                "details": "Empty file - no headers found",
                            }
                        )
                        if emitter and resource_id:
                            emit_otel_span(
                                emitter,
                                resource_id,
                                f"{OTelNames.CHK_FILE_VAL}: {fname}",
                                file_start_time,
                                get_time_nano(),
                                parent_span_id=parent_span_id,
                                span_id=file_span_id,
                                attributes={
                                    OTelNames.ATTR_VALIDATION_LEVEL: "schema",
                                    OTelNames.ATTR_FILE_NAME: fname,
                                    "error": "Empty File",
                                },
                                status_code="ERROR",
                                trace_id=trace_id,
                            )

            except Exception as e:
                results.append(
                    {
                        "name": f"File Schema Check: {fname}",
                        "status": "FAILED",
                        "details": f"Error reading file: {e}",
                    }
                )
                if emitter and resource_id and file_start_time is not None:
                    emit_otel_span(
                        emitter,
                        resource_id,
                        f"{OTelNames.CHK_FILE_VAL}: {fname}",
                        file_start_time,
                        get_time_nano(),
                        parent_span_id=parent_span_id,
                        span_id=file_span_id,
                        attributes={
                            OTelNames.ATTR_VALIDATION_LEVEL: "schema",
                            OTelNames.ATTR_FILE_NAME: fname,
                            "error": str(e),
                        },
                        status_code="ERROR",
                        trace_id=trace_id,
                    )
        else:
            pass
    return results


def check_file_extensions(data_dir):
    """Check if configured files have .csv extension."""
    extension_errors = []
    for key, filename in FILES.items():
        if os.path.exists(find_file(data_dir, filename)):
            if not filename.lower().endswith(".csv"):
                extension_errors.append(
                    f"{filename}: Invalid extension (Expected .csv)"
                )
    return extension_errors


def check_cgm_metadata_consistency(data_dir):
    """Check if files listed in cgm_file_metadata exists in the folder."""
    results = []
    cgm_meta_filename = FILES.get("cgm_file_metadata")
    if not cgm_meta_filename:
        return []

    cgm_meta_path = find_file(data_dir, cgm_meta_filename)
    if os.path.exists(cgm_meta_path):
        try:
            with open(cgm_meta_path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                if "file_name" not in reader.fieldnames:
                    return [
                        {
                            "name": "CGM Metadata Schema Check",
                            "status": "SKIPPED",
                            "details": "file_name column missing in metadata",
                        }
                    ]

                for row in reader:
                    expected_file = row.get("file_name")
                    if expected_file:
                        expected_file = expected_file.strip()
                        if not expected_file.lower().endswith(".csv"):
                            expected_file_with_ext = expected_file + ".csv"
                        else:
                            expected_file_with_ext = expected_file

                        target_path = find_file(data_dir, expected_file_with_ext)
                        check_name = f"CGM File Presence: {expected_file}"
                        if os.path.exists(target_path):
                            results.append(
                                {
                                    "name": check_name,
                                    "status": "PASSED",
                                    "details": f"File found in {data_dir}",
                                }
                            )
                        else:
                            results.append(
                                {
                                    "name": check_name,
                                    "status": "FAILED",
                                    "details": f"File listed in {cgm_meta_filename} is missing from disk",
                                }
                            )
        except Exception as e:
            results.append(
                {
                    "name": "CGM Metadata Read",
                    "status": "FAILED",
                    "details": f"Error reading {cgm_meta_filename}: {e}",
                }
            )
    return results


def check_cgm_data_integrity(data_dir):
    """Validate that CGM data files referenced in metadata contain data rows."""
    results = []
    cgm_meta_filename = FILES.get("cgm_file_metadata")
    if not cgm_meta_filename:
        return []

    cgm_meta_path = find_file(data_dir, cgm_meta_filename)
    if not os.path.exists(cgm_meta_path):
        return []

    try:
        with open(cgm_meta_path, "r", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            if "file_name" not in reader.fieldnames:
                return [
                    {
                        "name": "CGM Data Integrity Check",
                        "status": "SKIPPED",
                        "details": "file_name column not found",
                    }
                ]

            rows = list(reader)
            if not rows:
                return [
                    {
                        "name": "CGM Data Integrity Check",
                        "status": "FAILED",
                        "details": "cgm_file_metadata.csv has no data rows",
                    }
                ]

            for row in rows:
                expected_file = row.get("file_name")
                if expected_file:
                    expected_file = expected_file.strip()
                    if not expected_file.lower().endswith(".csv"):
                        expected_file_with_ext = expected_file + ".csv"
                    else:
                        expected_file_with_ext = expected_file

                    target_path = find_file(data_dir, expected_file_with_ext)
                    base_name = os.path.splitext(expected_file)[0]
                    check_name = f"CGM Data Integrity: {base_name}"

                    if os.path.exists(target_path):
                        try:
                            with open(target_path, "r", encoding="utf-8-sig") as df:
                                data_reader = csv.reader(df)
                                try:
                                    next(data_reader)  # header
                                    next(data_reader)  # first row
                                    results.append(
                                        {
                                            "name": check_name,
                                            "status": "PASSED",
                                            "details": f"Data rows detected for {base_name}",
                                        }
                                    )
                                except StopIteration:
                                    results.append(
                                        {
                                            "name": check_name,
                                            "status": "FAILED",
                                            "details": f"File {expected_file_with_ext} is empty or header only",
                                        }
                                    )
                        except Exception as e:
                            results.append(
                                {
                                    "name": check_name,
                                    "status": "FAILED",
                                    "details": f"Error reading {expected_file_with_ext}: {e}",
                                }
                            )
                    else:
                        results.append(
                            {
                                "name": check_name,
                                "status": "FAILED",
                                "details": f"File {expected_file_with_ext} not found",
                            }
                        )
    except Exception as e:
        results.append(
            {
                "name": "CGM Data Integrity Check",
                "status": "FAILED",
                "details": f"Error reading metadata: {e}",
            }
        )
    return results


def check_meal_data_consistency(data_dir):
    """Check if meal data files referenced in metadata exist on disk."""
    results = []
    meal_meta = FILES.get("meal_file_metadata")
    path = find_file(data_dir, meal_meta)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                checked = set()
                for row in reader:
                    fname = row.get("file_name", "").strip()
                    if not fname:
                        continue
                    if not fname.lower().endswith(".csv"):
                        fname += ".csv"
                    if fname in checked:
                        continue
                    checked.add(fname)
                    tpath = find_file(data_dir, fname)
                    check_name = f"Meal File Presence: {fname}"
                    if os.path.exists(tpath):
                        results.append(
                            {"name": check_name, "status": "PASSED", "details": "Found"}
                        )
                    else:
                        results.append(
                            {
                                "name": check_name,
                                "status": "FAILED",
                                "details": "Missing",
                            }
                        )
        except Exception as e:
            results.append(
                {"name": "Meal Metadata Read", "status": "FAILED", "details": str(e)}
            )
    return results


def check_fitness_data_consistency(data_dir):
    """Check if fitness data files referenced in metadata exist on disk."""
    results = []
    fit_meta = FILES.get("fitness_file_metadata")
    path = find_file(data_dir, fit_meta)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                checked = set()
                for row in reader:
                    fname = row.get("file_name", "").strip()
                    if not fname:
                        continue
                    if not fname.lower().endswith(".csv"):
                        fname += ".csv"
                    if fname in checked:
                        continue
                    checked.add(fname)
                    tpath = find_file(data_dir, fname)
                    check_name = f"Fitness File Presence: {fname}"
                    if os.path.exists(tpath):
                        results.append(
                            {"name": check_name, "status": "PASSED", "details": "Found"}
                        )
                    else:
                        results.append(
                            {
                                "name": check_name,
                                "status": "FAILED",
                                "details": "Missing",
                            }
                        )
        except Exception as e:
            results.append(
                {"name": "Fitness Metadata Read", "status": "FAILED", "details": str(e)}
            )
    return results


def check_meal_data_integrity(data_dir):
    """Validate that meal data files contain actual data rows."""
    results = []
    meta = FILES.get("meal_file_metadata")
    path = find_file(data_dir, meta)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                checked = set()
                for row in reader:
                    fname = row.get("file_name", "").strip()
                    if not fname:
                        continue
                    if not fname.lower().endswith(".csv"):
                        fname += ".csv"
                    if fname in checked:
                        continue
                    checked.add(fname)
                    tpath = find_file(data_dir, fname)
                    name = f"Meal Integrity: {fname}"
                    if os.path.exists(tpath):
                        with open(tpath, "r") as df:
                            dr = csv.reader(df)
                            try:
                                next(dr)
                                next(dr)
                                results.append(
                                    {
                                        "name": name,
                                        "status": "PASSED",
                                        "details": "Data OK",
                                    }
                                )
                            except StopIteration:
                                results.append(
                                    {
                                        "name": name,
                                        "status": "FAILED",
                                        "details": "Empty",
                                    }
                                )
                    else:
                        results.append(
                            {"name": name, "status": "FAILED", "details": "Missing"}
                        )
        except Exception as e:
            results.append(
                {"name": "Meal Integrity Check", "status": "FAILED", "details": str(e)}
            )
    return results


def check_fitness_data_integrity(data_dir):
    """Validate that fitness data files contain actual data rows."""
    results = []
    meta = FILES.get("fitness_file_metadata")
    path = find_file(data_dir, meta)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                checked = set()
                for row in reader:
                    fname = row.get("file_name", "").strip()
                    if not fname:
                        continue
                    if not fname.lower().endswith(".csv"):
                        fname += ".csv"
                    if fname in checked:
                        continue
                    checked.add(fname)
                    tpath = find_file(data_dir, fname)
                    name = f"Fitness Integrity: {fname}"
                    if os.path.exists(tpath):
                        with open(tpath, "r", encoding="utf-8") as df:
                            dr = csv.reader(df)
                            try:
                                next(dr)
                                next(dr)
                                results.append(
                                    {
                                        "name": name,
                                        "status": "PASSED",
                                        "details": "Data OK",
                                    }
                                )
                            except StopIteration:
                                results.append(
                                    {
                                        "name": name,
                                        "status": "FAILED",
                                        "details": "Empty",
                                    }
                                )
                    else:
                        results.append(
                            {"name": name, "status": "FAILED", "details": "Missing"}
                        )
        except Exception as e:
            results.append(
                {
                    "name": "Fitness Integrity Check",
                    "status": "FAILED",
                    "details": str(e),
                }
            )
    return results


def check_required_files(data_dir):
    """Check if all mandatory files exist."""
    missing_files = []
    for stream in MANDATORY_FILE_CHECK_STREAMS:
        fname = FILES.get(stream)
        if fname and not os.path.exists(find_file(data_dir, fname)):
            missing_files.append(fname)
    if os.path.exists(find_file(data_dir, FILES.get("meal_data", "meal_data.csv"))):
        if not os.path.exists(find_file(data_dir, FILES["meal_file_metadata"])):
            missing_files.append(FILES["meal_file_metadata"])
    if os.path.exists(
        find_file(data_dir, FILES.get("fitness_data", "fitness_data.csv"))
    ):
        if not os.path.exists(find_file(data_dir, FILES["fitness_file_metadata"])):
            missing_files.append(FILES["fitness_file_metadata"])
    return missing_files


class StateManager:
    """Manages Singer state bookmarks for resume-ability."""

    def __init__(self, state_path: Optional[str] = None):
        self.state = {}
        self.state_path = state_path
        if state_path and os.path.exists(state_path):
            try:
                with open(state_path, "r", encoding="utf-8") as f:
                    loaded = json.load(f)
                    self.state = (
                        loaded.get("bookmarks", {}) if isinstance(loaded, dict) else {}
                    )
            except Exception as e:
                LOGGER.warning(f"Failed to load state from {state_path}: {e}")

    def get_bookmark(self, stream: str, key: str) -> Optional[str]:
        """Retrieve bookmark value for a specific stream and key."""
        return self.state.get(stream, {}).get(key)

    def update_bookmark(self, stream: str, key: str, value: str):
        """Update bookmark value for a specific stream and key."""
        if stream not in self.state:
            self.state[stream] = {}
        self.state[stream][key] = value

    def emit_state(self):
        """Standard Singer STATE message."""
        print(json.dumps({"type": "STATE", "value": {"bookmarks": self.state}}))
        sys.stdout.flush()


# --- 5. DATA PROCESSING ---
def normalize_timestamp(ts: str) -> str:
    """Normalize timestamp string to ISO 8601 format."""
    if not ts:
        return ""
    if "T" in ts:
        return ts
    # Handle "2018-01-01 12:00:00" -> ISO
    try:
        # Simple heuristic for common formats
        if " " in ts:
            dt = datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")
            return dt.isoformat() + "Z"
        return ts
    except Exception:
        return ts


def process_cgm_tracing(
    emitter: ValidatingDRHLoader, data_dir: str, state: StateManager
):
    """
    Optimized: Efficiently streams CGM data using a single-pass approach per file.
    Groups metadata by file_name to avoid redundant I/O and uses O(1) matching.
    """
    meta_file = os.path.join(data_dir, "cgm_file_metadata.csv")
    if not os.path.exists(meta_file):
        LOGGER.info("No cgm_file_metadata.csv found, skipping CGM tracing.")
        return

    # 1. Load and Group Metadata by file_name
    files_to_patients = {}
    with open(meta_file, "r", encoding="utf-8-sig") as mf:
        meta_reader = csv.DictReader(mf)
        for row in meta_reader:
            fname = row.get("file_name", "").strip()
            if not fname:
                continue
            if not fname.lower().endswith(".csv"):
                fname += ".csv"

            fname = os.path.basename(fname)

            p_id = row.get("patient_id")
            if fname not in files_to_patients:
                files_to_patients[fname] = []

            row["_last_processed"] = state.get_bookmark("cgm_tracing", p_id)
            files_to_patients[fname].append(row)

    # 2. Process Files in a Single Pass
    start_time = get_time_nano()
    span_id, _ = emit_otel_span(
        emitter,
        emitter.otel_resource_id,
        OTelNames.CAT_CGM_INTEGRITY,
        start_time,
        start_time,
        trace_id=emitter.trace_id,
    )

    try:
        for fname, patient_list in files_to_patients.items():
            data_path = find_file(data_dir, fname)
            if not os.path.exists(data_path):
                LOGGER.warning(
                    f"Data file referenced in metadata not found: {data_path}"
                )
                continue

            LOGGER.info(
                f"Scanning {fname} (Single-pass for {len(patient_list)} patients)..."
            )

            # Build O(1) fast lookup map for this file
            # pid_col -> {raw_csv_value -> p_meta}
            fast_lookup = {}
            max_ts_map = {}

            for p_meta in patient_list:
                p_id = p_meta.get("patient_id")
                study_id = p_meta.get("study_id", "")
                pid_col = p_meta.get("map_field_of_patient_id", "PtID")

                bucket = fast_lookup.setdefault(pid_col, {})
                # Direct match
                bucket[p_id] = p_meta
                # Strip study-id prefix if present
                if study_id and p_id.startswith(f"{study_id}-"):
                    raw_stripped = p_id[len(study_id) + 1 :]
                    bucket[raw_stripped] = p_meta

                max_ts_map[p_id] = p_meta["_last_processed"]

            with open(data_path, "r", encoding="utf-8-sig") as df:
                reader = csv.DictReader(df)
                chunk_count = 0

                for d_row in reader:
                    # O(1) Routing
                    for pid_col, bucket in fast_lookup.items():
                        raw_val = d_row.get(pid_col)
                        if not raw_val:
                            continue

                        p_meta = bucket.get(raw_val)
                        if not p_meta:
                            continue

                        # Match Found!
                        p_id = p_meta.get("patient_id")
                        study_id = p_meta.get("study_id")
                        col_date = p_meta.get("map_field_of_cgm_date")
                        col_val = p_meta.get("map_field_of_cgm_value")
                        last_ts = p_meta["_last_processed"]
                        tenant_id = os.environ.get(
                            "TENANT_ID", p_meta.get("tenant_id", "")
                        )

                        raw_ts = d_row.get(col_date)
                        ts = normalize_timestamp(raw_ts)

                        if not ts or (last_ts and ts <= last_ts):
                            continue

                        val = d_row.get(col_val)
                        if not val:
                            continue

                        record = {
                            "tenant_id": tenant_id,
                            "study_id": study_id,
                            "participant_id": p_id,
                            "Date_Time": ts,
                            "CGM_Value": float(val),
                        }
                        emitter.emit_record("combined_cgm_tracing", record)

                        if not max_ts_map[p_id] or ts > max_ts_map[p_id]:
                            max_ts_map[p_id] = ts

                        chunk_count += 1
                        if chunk_count % 100000 == 0:
                            for pid, m_ts in max_ts_map.items():
                                if m_ts:
                                    state.update_bookmark("cgm_tracing", pid, m_ts)
                            state.emit_state()

            for pid, m_ts in max_ts_map.items():
                if m_ts:
                    state.update_bookmark("cgm_tracing", pid, m_ts)

        emit_otel_span(
            emitter,
            emitter.otel_resource_id,
            OTelNames.CAT_CGM_INTEGRITY,
            start_time,
            get_time_nano(),
            span_id=span_id,
            trace_id=emitter.trace_id,
            status_code="OK",
        )

    except Exception as e:
        LOGGER.error(f"Critical error in CGM streaming: {e}")
        emit_otel_span(
            emitter,
            emitter.otel_resource_id,
            OTelNames.CAT_CGM_INTEGRITY,
            start_time,
            get_time_nano(),
            span_id=span_id,
            trace_id=emitter.trace_id,
            status_code="ERROR",
        )


def process_metadata_stream(
    emitter: ValidatingDRHLoader, data_dir: str, stream_name: str
):
    """Processes static metadata streams."""
    file_path = os.path.join(data_dir, f"{stream_name}.csv")
    if not os.path.exists(file_path):
        return

    tenant_id = os.environ.get("TENANT_ID")
    tenant_name = os.environ.get("TENANT_NAME")

    with open(file_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Inject tenant fields if missing
            if tenant_id and not row.get("tenant_id"):
                row["tenant_id"] = tenant_id
            if tenant_name and not row.get("tenant_name"):
                row["tenant_name"] = tenant_name
            emitter.emit_record(stream_name, row)


# --- 6. CORE LOGIC ---
def main():
    """Primary entry point for the Singer tap."""
    parser = argparse.ArgumentParser(description="Singer Tap for CGMacros Dataset")
    parser.add_argument("-c", "--config", help="Config file")
    parser.add_argument("-s", "--state", help="State file")
    parser.add_argument("--discover", action="store_true", help="Do discovery")
    args = parser.parse_args()

    # Base Trace Context
    root_trace_id = str(uuid.uuid4()).replace("-", "")
    root_span_id = str(uuid.uuid4()).replace("-", "")[:16]

    # Initialize Components
    emitter = ValidatingDRHLoader()
    emitter.trace_id = root_trace_id

    # Discovery
    if args.discover:
        for stream in ALL_STREAM_NAMES:
            schema = load_schema(stream)
            if schema:
                emitter.emit_schema(stream, schema, STREAM_KEYS.get(stream, []))
        return

    # OTel Resource
    try:
        otel_resource_id = emit_otel_resource(emitter)
        emitter.otel_resource_id = otel_resource_id
    except Exception as e:
        LOGGER.warning(f"Failed to emit OTel resource: {e}")
        otel_resource_id = "unknown"

    # Resolve Data Path
    data_dir = os.environ.get("STUDY_DATA_PATH")
    if args.config:
        try:
            with open(args.config, encoding="utf-8") as f:
                conf = json.load(f)
                if "study_data_path" in conf:
                    data_dir = conf["study_data_path"]
        except Exception as e:
            LOGGER.warning(f"Failed to load config file: {e}")

    # Root V&V Span
    root_vv_start = get_time_nano()
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.ROOT_VV,
        root_vv_start,
        root_vv_start,
        span_id=root_span_id,
        trace_id=root_trace_id,
    )

    if not data_dir:
        msg = "FATAL: STUDY_DATA_PATH environment variable or config 'study_data_path' not set."
        LOGGER.error(msg)
        emit_otel_log(emitter, otel_resource_id, "FATAL", msg)
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.ROOT_VV,
            root_vv_start,
            get_time_nano(),
            span_id=root_span_id,
            trace_id=root_trace_id,
            status_code="ERROR",
        )
        sys.exit(0)

    # 1. Emit Initial Schemas
    for stream in ALL_STREAM_NAMES:
        schema = load_schema(stream)
        if schema:
            emitter.emit_schema(stream, schema, STREAM_KEYS.get(stream, []))

    # --- START VALIDATION PIPELINE ---
    overall_status = "PASSED"
    vv_reports = []

    def fail_and_exit(category, details):
        """Log error and exit with non-zero status."""
        emit_otel_log(
            emitter, otel_resource_id, "ERROR", f"{category} FAILED: {details}"
        )
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.ROOT_VV,
            root_vv_start,
            get_time_nano(),
            span_id=root_span_id,
            trace_id=root_trace_id,
            status_code="ERROR",
        )
        sys.exit(0)

    # Check 1: Folder & Resource Scan
    s1 = get_time_nano()
    if not os.path.exists(data_dir) or not os.path.isdir(data_dir):
        fail_and_exit(
            OTelNames.CAT_FOLDER_SCAN, f"Directory does not exist: {data_dir}"
        )

    file_count = len(
        [
            f
            for f in os.listdir(data_dir)
            if os.path.isfile(os.path.join(data_dir, f)) and f.endswith(".csv")
        ]
    )
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_FOLDER_SCAN,
        s1,
        get_time_nano(),
        parent_span_id=root_span_id,
        attributes={"file_count": file_count},
        trace_id=root_trace_id,
    )
    vv_reports.append(
        {
            "name": OTelNames.CAT_FOLDER_SCAN,
            "status": "PASSED",
            "details": f"Found {file_count} files",
        }
    )

    # Check 2: Mandatory File Presence
    s2 = get_time_nano()
    missing_files = check_required_files(data_dir)
    if missing_files:
        fail_and_exit(
            OTelNames.CAT_MANDATORY_FILES, f"Missing required files: {missing_files}"
        )
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_MANDATORY_FILES,
        s2,
        get_time_nano(),
        parent_span_id=root_span_id,
        trace_id=root_trace_id,
    )
    vv_reports.append(
        {"name": OTelNames.CAT_MANDATORY_FILES, "status": "PASSED", "details": "OK"}
    )

    # Check 3: File Extension Validation
    s3 = get_time_nano()
    ext_errors = check_file_extensions(data_dir)
    if ext_errors:
        fail_and_exit(OTelNames.CAT_EXTENSION_CHECK, "; ".join(ext_errors))
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_EXTENSION_CHECK,
        s3,
        get_time_nano(),
        parent_span_id=root_span_id,
        trace_id=root_trace_id,
    )
    vv_reports.append(
        {"name": OTelNames.CAT_EXTENSION_CHECK, "status": "PASSED", "details": "OK"}
    )

    # Check 4: File Schema Check (4.1.a - 4.1.d)
    s4 = get_time_nano()
    span_id4, _ = emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_SCHEMA_VALIDATION,
        s4,
        s4,
        parent_span_id=root_span_id,
        trace_id=root_trace_id,
    )

    fk_validator = ForeignKeyValidator()
    schema_results = check_file_headers(
        data_dir,
        emitter,
        otel_resource_id,
        parent_span_id=span_id4,
        trace_id=root_trace_id,
        fk_validator=fk_validator,
    )
    vv_reports.extend(schema_results)

    if any(r["status"] == "FAILED" for r in schema_results):
        overall_status = "FAILED"
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.CAT_SCHEMA_VALIDATION,
            s4,
            get_time_nano(),
            span_id=span_id4,
            trace_id=root_trace_id,
            status_code="ERROR",
        )
        fail_and_exit("Check 4: Data Schema", "One or more files have schema errors")

    # Global FK Validation (Check 4.1.d)
    fk_start = get_time_nano()
    fk_violations = fk_validator.validate()
    fk_status = "PASSED" if not fk_violations else "FAILED"
    vv_reports.append(
        {
            "name": OTelNames.CHK_FK_INTEGRITY,
            "status": fk_status,
            "details": "; ".join(fk_violations[:5]) if fk_violations else "OK",
        }
    )
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CHK_FK_INTEGRITY,
        fk_start,
        get_time_nano(),
        parent_span_id=span_id4,
        attributes={OTelNames.ATTR_ERROR_COUNT: len(fk_violations)},
        status_code="OK" if not fk_violations else "ERROR",
        trace_id=root_trace_id,
    )

    if fk_violations:
        overall_status = "FAILED"
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.CAT_SCHEMA_VALIDATION,
            s4,
            get_time_nano(),
            span_id=span_id4,
            trace_id=root_trace_id,
            status_code="ERROR",
        )
        fail_and_exit(OTelNames.CHK_FK_INTEGRITY, "Foreign key violations detected")

    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_SCHEMA_VALIDATION,
        s4,
        get_time_nano(),
        span_id=span_id4,
        trace_id=root_trace_id,
        status_code="OK",
    )

    # Check 5: CGM Metadata Consistency
    s5 = get_time_nano()
    cgm_meta_results = check_cgm_metadata_consistency(data_dir)
    vv_reports.extend(cgm_meta_results)
    if any(r["status"] == "FAILED" for r in cgm_meta_results):
        fail_and_exit(OTelNames.CAT_CGM_TRACE_METADATA, "CGM Metadata inconsistent")
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_CGM_TRACE_METADATA,
        s5,
        get_time_nano(),
        parent_span_id=root_span_id,
        trace_id=root_trace_id,
    )

    # Check 6: CGM Data Integrity
    s6 = get_time_nano()
    cgm_int_results = check_cgm_data_integrity(data_dir)
    vv_reports.extend(cgm_int_results)
    if any(r["status"] == "FAILED" for r in cgm_int_results):
        fail_and_exit(OTelNames.CAT_CGM_INTEGRITY, "CGM Data files empty or missing")
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.CAT_CGM_INTEGRITY,
        s6,
        get_time_nano(),
        parent_span_id=root_span_id,
        trace_id=root_trace_id,
    )

    # Optional Bundle: Meal & Fitness
    meal_meta_path = find_file(data_dir, FILES.get("meal_file_metadata"))
    if os.path.exists(meal_meta_path):
        s7 = get_time_nano()
        meal_c_results = check_meal_data_consistency(data_dir)
        vv_reports.extend(meal_c_results)
        if all(r["status"] == "PASSED" for r in meal_c_results):
            s8 = get_time_nano()
            meal_i_results = check_meal_data_integrity(data_dir)
            vv_reports.extend(meal_i_results)
            if any(r["status"] == "FAILED" for r in meal_i_results):
                overall_status = "FAILED"
            emit_otel_span(
                emitter,
                otel_resource_id,
                OTelNames.CAT_MEAL_INTEGRITY,
                s8,
                get_time_nano(),
                parent_span_id=root_span_id,
                trace_id=root_trace_id,
            )
        else:
            overall_status = "FAILED"
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.CAT_MEAL_METADATA,
            s7,
            get_time_nano(),
            parent_span_id=root_span_id,
            trace_id=root_trace_id,
        )

    fit_meta_path = find_file(data_dir, FILES.get("fitness_file_metadata"))
    if os.path.exists(fit_meta_path):
        s9 = get_time_nano()
        fit_c_results = check_fitness_data_consistency(data_dir)
        vv_reports.extend(fit_c_results)
        if all(r["status"] == "PASSED" for r in fit_c_results):
            s10 = get_time_nano()
            fit_i_results = check_fitness_data_integrity(data_dir)
            vv_reports.extend(fit_i_results)
            if any(r["status"] == "FAILED" for r in fit_i_results):
                overall_status = "FAILED"
            emit_otel_span(
                emitter,
                otel_resource_id,
                OTelNames.CAT_FITNESS_INTEGRITY,
                s10,
                get_time_nano(),
                parent_span_id=root_span_id,
                trace_id=root_trace_id,
            )
        else:
            overall_status = "FAILED"
        emit_otel_span(
            emitter,
            otel_resource_id,
            OTelNames.CAT_FITNESS_METADATA,
            s9,
            get_time_nano(),
            parent_span_id=root_span_id,
            trace_id=root_trace_id,
        )

    # Emit Reports
    # for r in vv_reports:
    # emitter.emit_record("drh_diagnostics", r)

    if overall_status == "FAILED":
        fail_and_exit("V&V Pipeline", "One or more data integrity checks failed")

    # Final Report
    duration = (get_time_nano() - root_vv_start) / 1e9

    # --- START DATA EMISSION ---
    state = StateManager(args.state)

    # 1. Static Metadata
    for stream in MANDATORY_STREAM_NAMES:
        process_metadata_stream(emitter, data_dir, stream)

    # 2. Support Metadata
    for stream in [
        "institution",
        "lab",
        "investigator",
        "publication",
        "author",
        "site",
    ]:
        process_metadata_stream(emitter, data_dir, stream)

    # 3. High-Volume Tracing
    process_cgm_tracing(emitter, data_dir, state)

    # 4. Final State
    state.emit_state()

    # Success Span
    emit_otel_span(
        emitter,
        otel_resource_id,
        OTelNames.ROOT_VV,
        root_vv_start,
        get_time_nano(),
        span_id=root_span_id,
        trace_id=root_trace_id,
        status_code="OK",
    )
    emit_otel_metric(
        emitter, otel_resource_id, OTelNames.METRIC_PASS_COUNT, len(vv_reports)
    )
    emit_otel_metric(
        emitter, otel_resource_id, OTelNames.METRIC_VALIDATION_DURATION, duration
    )

    LOGGER.info("Tap processing complete.")


if __name__ == "__main__":
    main()
